//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ODEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rezervasyonlar
    {
        public int Rezervasyon_Id { get; set; }
        public Nullable<int> Arac_Id { get; set; }
        public string Tc_Kimlik { get; set; }
        public string Ad_Soyad { get; set; }
        public Nullable<System.DateTime> Alma_Tarihi { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<decimal> Ucret { get; set; }
        public string Iptal_Mi { get; set; }
        public Nullable<System.DateTime> Iptal_Tarihi { get; set; }
    }
}
